# Generated by Django 3.1.3 on 2021-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('song_id', models.AutoField(primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=40)),
                ('song_file', models.FileField(upload_to='songs/')),
                ('song_singer', models.CharField(max_length=30)),
                ('song_desc', models.CharField(max_length=50)),
            ],
        ),
    ]
