# Generated by Django 3.2.4 on 2021-11-11 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_song_song_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='player.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_singer',
            field=models.CharField(max_length=30),
        ),
    ]
