# Generated by Django 3.2.4 on 2021-11-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_user_last_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
