# Generated by Django 3.2.4 on 2021-11-12 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_auto_20211112_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
