# Generated by Django 3.1.3 on 2021-11-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_remove_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user_id',
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='player.user'),
            preserve_default=False,
        ),
    ]
