# Generated by Django 3.2.4 on 2021-11-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_auto_20211124_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
